
server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
        http-only: false
#
# Spring组件配置
spring:
  # session 失效时间
  session:
    store-type: redis
  jackson:
    time-zone: GMT+8
    date-format: java.text.SimpleDateFormat
  application:
    name: fishmanChat-backend
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/software
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 030610CHENyu
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  #redis配置
  redis:
    port: 6379
    host: localhost
    database: 0
    #修改redis的数据库，redis带有16个数据库

# 后台监控的登录信息
loginAccount:
  username: admin
  password: admin

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #SQL的日志打印
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx


knife4j:
  enable: true
  openapi:
    title: 接口文档
    description: "共享雨伞文档"
    email: cy13692810010@163.com
    version: v2.0.0
    concat: fishman
    group:
      fishmanChat:
        group-name: fishmanChat
        api-rule: package
        api-rule-resources:
          - com.fishman.controller
# Token生成
token:
  SECRET_KEY: fishman
  EXPIRATION_TIME: 864_000_000

